---
# Playbook для розгортання Cinema Club
# Last updated: 2025-11-12
- name: Deploy Cinema Club Application
  hosts: cinema
  become: yes
  gather_facts: no
  
  vars:
    # Змінні проекту
    app_name: cinema-club
    app_port: 8080
    repo_url: https://github.com/ivansstef/CinemaClub.git
    app_dir: /opt/cinema-club
    
  roles:
    - cinema
