---
# Playbook для деплою Cinema Club додатку
# Відповідає тільки за запуск/оновлення додатку

- name: Deploy Cinema Club Application
  hosts: cinema
  become: yes
  gather_facts: no
  
  vars:
    # Змінні проекту
    app_name: cinemaclub
    app_port: 8080
    app_dir: /opt/cinema-club
    docker_image_tag: "{{ image_tag | default('latest') }}"
    
  roles:
    - application
